### ISSUE TITLE
chunker.Next with no allocations

### ISSUE THREAD

**Issue by vitalyisaev2** [restic/chunker#17]
```Chunker.Next([]byte)``` consumes a slice on the every iteration in order to copy data for a particular chunk from the internal buffer. In Restic ```sync.Pool``` is used to decrease GC pressure, but there are a lot of use-cases where it's possible to read the initial ```io.Reader``` again and reuse the memory it occupies. The resulting ```Chunk.Data``` will be just a reference to the initial data slice, not a copy of it. 

I would like to propose additional method (smth. like ```Chunker.NextNoCopy()``` or ```Chunker.NextMeta()```) that will produce ```Chunk``` with empty ```Data```. Client will be responsible to fill the ```Data``` on his own (according to the ```Chunk``` metainformation - ```Start``` and ```Length```). Would you agree with  such interface extension?

Kind regards, 
Vitaly

**Comment by fd0** [comment]
We used to have exactly that in restic, but it turns out that's a bad idea (at least for backup software):
 * When the file we're reading changes in between chunking and reading, the data is bogus
 * The Linux kernel has a heuristic: When data from the disc is read twice in a row, the kernel decides that this particular data is valuable and will be read again in the future. So it decides that other data in the disc cache should be flushed in order to make more room for such valuable data. In the end, this made many systems unusable.

You can use the chunker with one slice, and always pass in the same slice. The `sync.Pool` in restic is used for other reasons.

What's your use case?

**Comment by vitalyisaev2** [comment]
Sorry, I should have described my use case more properly. First of all - it has nothing to do with filesystem, therefore file inconsistency and kernel disk cache effects are not taken into account, I use `restic/chunker` as a standalone library.

Consider we have a stream of binary data fragments, and Content Defined Chunking is just a single level within a data processing pipeline. Different processing layers perform CPU-bound operations and work in distinct goroutines. Every chunk discovered by ```restic/chunker``` is passed immediately to the downstream layer. In short, there are several long-running goroutines exchanging the byte slices via channels:

```go
package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"sync"

	"github.com/restic/chunker"
)

func proccessing(input <-chan []byte) {

	wg := &sync.WaitGroup{}
	wg.Add(2)

	// channel connects two different data processing layers
	// into a single pipeline
	pipeline := make(chan []byte)

	// Stage 1: Content Defined Chunking
	go func() {

		defer func() {
			wg.Done()
			close(pipeline)
		}()

		var (
			pol    = chunker.Pol(0x123)
			chnker = chunker.New(nil, pol)
		)

		for {
			// Obtain new data part from incoming channel
			data, ok := <-input
			if !ok {
				return
			}
                        // Reset chunker with a new reader
			chnker.Reset(bytes.NewReader(data), pol)

			for {
				// NextMeta requires no data allocation, it returns only 
                                // metainformation about a chunk.
                                // Client is responsible to create a data chunk taking into account
                                // information provided by chunker.
				meta, err := chnker.NextMeta()
				if err != nil {
					break
				}
				// Chunk simply references the initial data slice
				chunk := data[meta.Start : meta.Start+meta.Length]
                                // Send chunk to the next layer
				pipeline <- chunk
			}
		}

	}()

	// Stage 2: Checksum computation
	go func() {
		hash := sha256.New()
		defer wg.Done()
		for {
                        // obtain chunk from Content Defined Chunking layer
			chunk, ok := <-pipeline
			if !ok {
				return
			}
                        // compute chunk's checksum
			hash.Reset()
			io.Copy(hash, bytes.NewReader(chunk))
			fmt.Printf("%x", hash.Sum(nil))
		}
	}()

	wg.Wait()
}

```

So, in my case ```io.Reader``` has underlying byte slice which is guaranteed to be immutable and can be reused again. That's why I don't want to allocate new slice every time, I just want ```Chunker``` to produce chunk coordinates.

> You can use the chunker with one slice, and always pass in the same slice. The sync.Pool in restic is used for other reasons.
Unfortunately, I can't pass the same slice every time I call ```Chunker.Next```, because this slice is passed to other reading goroutine, and this will cause data race (```Chunker``` goroutine is writing again, while ```Checksum``` is reading).

> The sync.Pool in restic is used for other reasons.
Could you please explain these reasons? I thought that `sync.Pool` is mainly used to decrease number of allocations / frees.

**Comment by fd0** [comment]
Thanks for the explanation, that makes sense now.

> Could you please explain these reasons? I thought that sync.Pool is mainly used to decrease number of allocations / frees.

You're right, what I meant was that the sync.Pool is there to decrease allocations in restic, there aren't any allocations in the chunker.

> Unfortunately, I can't pass the same slice every time I call Chunker.Next

You can, although that feels a bit clunky:

```go
		var (
			pol    = chunker.Pol(0x123)
			chnker = chunker.New(nil, pol)
			tmpBuf = make([]byte, maxChunkSize)
		)

		for {
			// Obtain new data part from incoming channel
			data, ok := <-input
			if !ok {
				return
			}
                        // Reset chunker with a new reader
			chnker.Reset(bytes.NewReader(data), pol)

			for {
				meta, err := chnker.Next(tmpBuf)
				if err != nil {
					break
				}
				// Chunk simply references the initial data slice
				// tmpBuf isn't used by following stages and can instantly be reused
				chunk := data[meta.Start : meta.Start+meta.Length]
                                // Send chunk to the next layer
				pipeline <- chunk
			}
		}
```

**Comment by vitalyisaev2** [comment]
> You can, although that feels a bit clunky.

Yeah, it's quite a dirty workaround :slightly_smiling_face: 

> What if we make the byte slice passed to Next() optional? If it's nil, nothing is copied. As long as that doesn't introduce a performance hit.

Do you mean changing interface from ```Next([]byte)``` to ```Next(...[]byte)```? Not proposing new method instead?

**Comment by fd0** [comment]
No, my suggestion was to allow calling `chunker.Next(nil)`.

**Comment by vitalyisaev2** [comment]
OK, sounds like a plan, I will try to work it out

**Comment by tv42** [comment]
I would suggest a separate method instead of `Next(nil)`. `Next(nil)` looks awfully lot like e.g. `append`, `hash.Hash.Sum`, etc; there's a pretty strong convention that in buffer-reuse scenarios like that, `nil` means "please allocate it yourself".

**Comment by fd0** [comment]
Is this issue still relevant? Anybody up for a PR which maybe adds a new method, e.g. `NextHashOnly()` (name to be discussed) or something similar? Or can we close this issue?

**Comment by vitalyisaev2** [comment]
> Is this issue still relevant?

I think you can close it. Unfortunately I was not able to find time for this optimization...

**Comment by fd0** [comment]
Ok, cool, thanks for the feedback! :)
