### ISSUE TITLE
Should I use chunker in production?

### ISSUE THREAD

**Issue by abhigyan-tiwari** [restic/chunker#23]
I'm to implement a file storage web application. We are planning to implement versioning of files soon. It will require diffing and we will store data in chunks for deduplication (we store old blocks with new blocks as revision). 

We will have client (smartphone, PC) based and server based deduplication both, as we'll have web uploads too. I had idea about executing chunker from our program which is not in go. We'll serve millions of users and will have petabyte scale data stores for users. 

Can I use chunker to accomplish above tasks and ship in production?

I also needed help in designing versioning index (pointers to chunks--bins) as I couldn't come with better versioning design. I faced pointers to block redundancy  as new version will have repeated old blocks with new blocks.

Thanks.

**Comment by fd0** [comment]
I'm not sure what you want from us. This library allows splitting a stream of bytes into chunks in a deterministic way, that's it. What you do with the chunks afterwards is up to you. Good luck.

**Comment by abhigyan-tiwari** [comment]
@fd0 Thanks for your response! One more question I had was should I perform segmentation for chunks? As they are already big from restic chunker. I'll not use the restic-backup, so will not be benefited by packs generation. we'll store chunk indexes inside RDBMS (is it good to use Key-value DB store?).
